[package]
name = "height-caculator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
color-eyre = { version = "0.6.1", features = ["url", "issue-url"] }
dialoguer = "0.10.1"
indicatif = "0.16.2"
